# calcular-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calcular-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calcular
  template:
    metadata:
      labels:
        app: calcular
    spec:
      containers:
      - name: calcular-container
        image: lujamx/calcular:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: calcular-service
spec:
  selector:
    app: calcular
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
