apiVersion: v1
kind: Service
metadata:
  name: microservices
spec:
  selector:
    app: microservices
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservices
  template:
    metadata:
      labels:
        app: microservices
    spec:
      containers:
        - name: metro
          image: lujamx/metro-service:latest
          ports:
            - containerPort: 3000
        - name: pie
          image: lujamx/pie-service:latest
          ports:
            - containerPort: 3001
        - name: pulgada
          image: lujamx/pulgada-service:latest
          ports:
            - containerPort: 3002
