# pie-service-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pie-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pie-service
  template:
    metadata:
      labels:
        app: pie-service
    spec:
      containers:
      - name: pie
        image: lujamx/pie-service:latest  # Ajusta esto a la ubicación de tu imagen
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: pie-service
spec:
  selector:
    app: pie-service
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3001
