# pulgada-service-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulgada-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pulgada-service
  template:
    metadata:
      labels:
        app: pulgada-service
    spec:
      containers:
      - name: pulgada
        image: lujamx/pulgada-service:latest  # Ajusta esto a la ubicación de tu imagen
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: pulgada-service
spec:
  selector:
    app: pulgada-service
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3002
